기초 라우팅 작업 및 디렉토리 세분화
DefCon-Apps/DefCon-FE pull request #1
Opened 2022-12-25 15:30 UTC by HarenKei

# Summary
- 페이지별 디렉토리 생성
- 페이지별 index.tsx 파일 생성하여 기초적인 코드 작성
- 최상위 index.tsx에서 기초적인 라우팅 테스트 코드 작성
- 프로젝트 페이지 > 각 프로젝트 페이지 동적 라우팅
- 함수형 컴포넌트 작성 방식 변경
- 헤더, 푸터 컴포넌트 생성

# Description
- pages 디렉토리 하위에 디자인, 프로젝트, 멤버, 개인정보 정책 페이지의 index.tsx 생성
- 각 index.tsx에 페이지를 나타낼 수 있는 테스트 코드 작성
- pages/index.tsx에서 각 페이지로 이동할 수 있는 테스트 라우팅 코드 작성, 작동 확인
- projectsPage/[projName] 생성으로 각 프로젝트별 뷰 페이지 동적 라우팅 구현
- export default function... 형태의 함수형 컴포넌트를 Arrow Function으로 모두 변경
- src/component 디렉토리 신규 생성하여 컴포넌트만을 다루고자 하였음. 이 하위에 헤더와 푸터 생성하였음.

# etc
이게 맞나 잘 모르겠네요.... 🤔

2022-12-25 22:38 UTC, rdg1029 approved these changes
😮👍

2022-12-26 03:03 UTC, yymin1022 requested changes
src/components 디렉터리를 src/Common 디렉터리로 하는건 어떨까요? 좀 더 직관적으로
그리고 pages 내 디렉터리들도 Page라는 키워드를 빼고 Design, Members, Privacy, Projects, ProjectDetail등으로 가면 어떨지

2022-12-26 03:03 UTC, yymin1022 commented on pages/_app.tsx
> +import Header from "../src/component/header";
header -> Header 로 대문자 고쳐주세요

2022-12-26 11:55 UTC, yymin1022 requested changes
Common 디렉터리 내 Component 구분을 제거해주시면 감사하겠습니다~

2022-12-26 12:09 UTC, yymin1022 approved these changes
고생하셨습니다~

2022-12-26 12:09 UTC, merged